name = "promo-codes-worker"
compatibility_date = "2025-03-21"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[build]
# Add googleapis and dotenv as external dependencies
external_modules = ["googleapis", "dotenv"]
